### ISSUE TITLE
[DOCS] Improve documentation

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/ss2-docs#18] opened 2024-09-25 06:03 UTC
## Issue Overview

Feel free to submit a PR on documentation improvements. This issue won't be assigned to anyone, Please request for review when you're done, also try not to overlap

- **Mainly explain features that the framework provides but they are not documented yet.**
- **Update some features that are outdated. Explain how to use this feature now**
- **Clean old features the the framework doesn't support anymore.**

Please avoid typo fixes, we prefer meaningful changes to the documentation.

Happy Hacking!

**Comment by ShantelPeters** [comment] 2024-09-25 17:50
@metalboyrick please i will like to take this up, this would be my first time contributing to this ecosystem.

**Comment by gregemax** [comment] 2024-09-26 09:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have experience working with JavaScript and have contributed to various open-source projects, focusing on code quality and documentation. My background will help me improve the clarity and accessibility of the documentation, making it easier for other developers to understand and contribute

### How I plan on tackling this issue
I would start by reviewing the existing documentation for gaps or unclear sections. Then, I’d propose improvements, such as adding examples, clarifying explanations, and ensuring consistency. I would submit a PR for review once the improvements are made

**Comment by thesledge04** [comment] 2024-09-26 09:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have a background in software development and experience with Python programming, particularly in building and maintaining applications using frameworks like Streamlit. My expertise includes:
I have experience in writing and improving documentation for various projects, ensuring clarity, consistency, and usability for developers and end-users alike.
Familiarity with web application architecture, enabling me to effectively document APIs, data structures, and user interfaces.
I prioritize user experience in my documentation, striving to make it intuitive and accessible, which helps users quickly understand and utilize the software.

### How I plan on tackling this issue
Approach to Submitting a Pull Request (PR) for Documentation Improvements:
Review Existing Documentation:
Start by thoroughly reading the current documentation, including README files, code comments, and any other relevant documentation provided in the repository.
Identify areas that are unclear, outdated, or missing crucial information that would benefit users or developers.
Make Notes on Improvement Areas:
Document specific sections that require clarification or expansion. This could include:
Explanation of key components and their functionalities.
Instructions for setting up the project or running tests.
Examples of how to use different features.
Descriptions of data structures or algorithms used in the code.
Any frequently asked questions (FAQs) that might help new users.
Draft Changes:
Write clear and concise documentation updates based on your notes. Focus on:
Using simple language that is easy to understand.
Maintaining a consistent format and style throughout the documentation.
Adding code snippets where applicable to illustrate points.
Ensuring that any technical jargon is defined.
Implement Changes in Codebase:
Make the necessary edits directly in the appropriate files within the codebase. Ensure that:
You follow any existing guidelines for documentation structure and formatting.
You do not introduce any errors into the documentation or code comments.
Test Your Changes:
If possible, preview the documentation locally to ensure that it renders correctly and that all links, code snippets, and formatting appear as intended.
Verify that changes do not interfere with the functionality of the code.
Create a Pull Request (PR):
Push your changes to a new branch in the repository.
Go to the repository on GitHub and create a new pull request, providing a clear title and description of the changes made. Include:
A summary of the improvements and the rationale behind them.
Any specific areas where you would like feedback or review from the maintainers.
Request for Review:
Once the PR is created, tag relevant collaborators or maintainers to review your changes. Ensure to mention in the comments that the PR focuses on documentation improvements.
Address Feedback:
Be open to feedback and willing to make additional changes based on reviewer comments. This collaborative approach ensures that the documentation is improved effectively.

**Comment by CollinsC1O** [comment] 2024-09-26 09:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello @metalboyrick I'm a front-end and also a blockchain developer with experience on technical writing and writing documentations 

### How I plan on tackling this issue
I will love to improve/implement the documentation

**Comment by Jemiiah** [comment] 2024-09-26 10:05
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I would love to work on this issue I have worked on about 6 different documentation issue on different repositories this is my OD Hack portfolio with over 50 contributions https://app.onlydust.com/u/Jemiiah I have a very good track record on docs issues here are some of the repositories I have worked on:
Flex-NFT-Marketplace/Flex-Marketplace-Contract#106
dragan2234/worldcoin-scroll-bridge#13
dragan2234/worldcoin-scroll-bridge#11
NethermindEth/StarknetByExample#200

**Comment by Kaminar-i** [comment] 2024-09-26 10:29
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
hello i am a blockchain developer
please can i work on this issue :) and would love to be a contributor


### How I plan on tackling this issue
i would love to work on this

**Comment by ScottyDavies** [comment] 2024-09-26 10:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have a strong background in technical writing and software development, with experience in creating and improving documentation for codebases

### How I plan on tackling this issue
To approach the documentation improvements, I would:

Thoroughly read the current documentation to identify areas for clarity, completeness, and consistency.

Check existing issues or discussions for any user-reported documentation gaps or suggestions.

Revise or add content to enhance explanations, examples, and structure, ensuring clarity and usability.

 Ensure that terminology and formatting align with the project's style guide.

 Once completed, I will submit a pull request and request a review, highlighting the key changes made.

**Comment by metalboyrick** [comment] 2024-09-26 12:38
Hi all, kindly state what part of the documentation you want to propose in this issue and you may submit a PR if it does not clash with the others. As I've stated in the description this issue would be open and will not be assigned to anyone

**Comment by Gift-Naomi** [comment] 2024-09-26 13:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged


I am a web3 developer/ Technical writer


### How I plan on tackling this issue
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
Flex-NFT-Marketplace/Flex-Marketplace-Contract@fc28412
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by PabloVillaplana** [comment] 2024-09-26 15:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community

### How I plan on tackling this issue
Documenting seems to me to be a fundamental part, I would like to be able to contribute to the documentation of this project by adding improvements that contribute and help the documentation.

**Comment by nov0ax** [comment] 2024-09-26 16:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I´m a front end developer with background on backend using Javascript, C# and other programing languages, I'm attention to detail person and have worked on documentation  of  processes and software workflow.

### How I plan on tackling this issue
I could check out the existing documentation and provide feedback based on the user experience of the environment/tools developed. I'd love contribuiting on my first issue to start this amazing OSS world.

**Comment by pheobeayo** [comment] 2024-09-26 16:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am Web3 frontend developer skilled in technical documentation and software developer. I have great understanding of technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully on open source projects like Stark Quest

### How I plan on tackling this issue
My Approach include Pull Request (PR) includes:
- Reviewing of existing Documentation:
by thorough reading the current documentation, including README files, code comments, and any other relevant documentation provided in the repository.
Identify areas that are unclear, outdated, or missing crucial information that would be of benefit to users and developers
- Make note of changes and define all code snippets and technical terms in simple terms.
- Create a Pull Request (PR)
- Request for a Review
- Make changes based on Review of the PR

**Comment by Pvsaint** [comment] 2024-09-26 17:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I'd like to work on this project, this would be my first project as a contributor.
I'm a front end and blockchain developer, with 3 years experience in react.

**Comment by Luluameh** [comment] 2024-09-28 00:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have experience in JavaScript development and technical writing. I’ve contributed to open-source projects by documenting features, updating outdated information, and improving clarity for developers.

### How I plan on tackling this issue
I’d start by reviewing the framework’s existing features and comparing them to the current documentation. I’d explain any undocumented features, update outdated sections, and remove deprecated content. I'd ensure the documentation is clear, concise, and up-to-date for developers

**Comment by ScottyDavies** [comment] 2024-09-28 21:54
Hello @metalboyrick can i please be assigned this task?

**Comment by Nadai2010** [comment] 2024-09-29 17:59
Hi @all, We remind you that this issue on documentation is open, no assignment is needed to submit the PR, today they have been updated with [version V3](https://github.com/Scaffold-Stark/ss2-docs/pull/17), please review and try to improve the current versions.

**Comment by vic-Gray** [comment] 2024-09-30 14:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have a solid background in software development with extensive experience in both front-end and back-end technologies. My skills include working with various programming languages and frameworks, allowing me to understand complex systems and identify areas for improvement. Additionally, I have experience in technical writing, which enables me to convey technical concepts clearly and concisely. My familiarity with documentation best practices will ensure that the documentation improvements I make are not only accurate but also user-friendly. This will ultimately enhance the overall developer experience for users of the framework.

### How I plan on tackling this issue
Step 1: Feature Identification
I would begin by reviewing the framework's codebase, release notes, and community discussions to identify features that are either undocumented or inadequately documented. This includes new features, enhancements, and common use cases that users may struggle with due to a lack of clear guidance.

Step 2: Update Outdated Information
Next, I would cross-reference existing documentation with the latest version of the framework to identify outdated features or usage patterns. I would update these sections to reflect current best practices and include clear, concise examples that demonstrate how to use the features effectively.

Step 3: Remove Deprecated Features
I would identify any features that the framework no longer supports and clean up the documentation by removing these references. In cases where alternatives are available, I would document these new methods clearly to guide users in transitioning from deprecated functionalities.

Step 4: Drafting Changes
I would draft the necessary changes in a structured manner, ensuring that each section is easy to read and understand. I would use code snippets to illustrate usage where applicable, ensuring the documentation is practical and actionable.

Step 5: Review and Submit PR
After making the changes, I would create a Pull Request (PR) and request a review from maintainers. In the PR description, I would clearly outline the changes made, including new features documented, updates to existing features, and any deprecated content removed. I would also check for any overlapping work with other contributors to avoid conflicts.

By following this structured approach, I aim to deliver meaningful improvements to the documentation, ensuring it serves as a valuable resource for all users of the framework.

**Comment by Dev-AndresGR** [comment] 2024-10-02 22:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
ss

### How I plan on tackling this issue
ss

**Comment by metalboyrick** [comment] 2024-10-03 13:42
Hi everyone, since we found that people might be clueless on what to improve on. We've decided to open up new issues that you can take. Feel free to apply through OD again for the issues. Thank you and apologies for the inconvenience!

NOTE: We will prioritize people who've applied to this issue and by order of time.

**Closed** 2024-10-08 21:03 UTC
Labels: documentation, help wanted, ODHack8
